test_that("Calculation mistake",{
  m <- matrix(c(9.698386, 4.303039, 6.102675, 9.151815, 5.784404,
                1.6320504, 1.2952817, 1.5789237, 1.1762649, 0.8169756,
                0.3167154, 0.5419347, 0.4492132, 0.6694728, 0.1725755),
              ncol = 3)
  expect_equal(pdf_chen(m[1,1], c(m[1,2], m[1,3])), 0)
  expect_equal(pdf_chen(m[2,1], c(m[2,2], m[2,3])), 3.002314e-174)
  expect_equal(pdf_chen(m[3,1], c(m[3,2], m[3,3])), 0)
  expect_equal(pdf_chen(m[4,1], c(m[4,2], m[4,3])), 0)
  expect_equal(pdf_chen(m[5,1], c(m[5,2], m[5,3])), 8.5649748575050097541e-05)

  # Values generated by runif and calculated using a known to work version of function.
})

