test_that("output", {
  set.seed(69)
  cvar <- cbind(df$cvar1, df$cvar2)
  df_test1 <- data.frame(y = rchen_rpr(100, list(0.7, cvar %*% matrix(c(1, 1)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test1, y ~ cvar1 + cvar2))
  df_test2 <- data.frame(y = rchen_rpr(100, list(0.3, cvar %*% matrix(c(0.4, 1)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test2, y ~ cvar1 + cvar2))
  df_test3 <- data.frame(y = rchen_rpr(100, list(0.5, cvar %*% matrix(c(1, 0.1)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test3, y ~ cvar1 + cvar2))
  df_test4 <- data.frame(y = rchen_rpr(100, list(1, cvar %*% matrix(c(0.5, 1.3)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test1, y ~ cvar1 + cvar2))
  df_test5 <- data.frame(y = rchen_rpr(100, list(0.1, cvar %*% matrix(c(0.4, 2)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test2, y ~ cvar1 + cvar2))
  df_test6 <- data.frame(y = rchen_rpr(100, list(2, cvar %*% matrix(c(2, 0.7)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test3, y ~ cvar1 + cvar2))
})

test_that("output with bootstrap", {
  set.seed(69)
  cvar <- cbind(df$cvar1, df$cvar2)
  df_test1 <- data.frame(y = rchen_rpr(100, list(0.7, cvar %*% matrix(c(1, 1)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test1, y ~ cvar1 + cvar2, n_bootstrap = 30))
  df_test2 <- data.frame(y = rchen_rpr(100, list(0.3, cvar %*% matrix(c(0.4, 1)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test2, y ~ cvar1 + cvar2, n_bootstrap = 30))
  df_test3 <- data.frame(y = rchen_rpr(100, list(0.5, cvar %*% matrix(c(1, 0.1)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test3, y ~ cvar1 + cvar2, n_bootstrap = 30))
  df_test4 <- data.frame(y = rchen_rpr(100, list(1, cvar %*% matrix(c(0.5, 1.3)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test1, y ~ cvar1 + cvar2, n_bootstrap = 30))
  df_test5 <- data.frame(y = rchen_rpr(100, list(0.1, cvar %*% matrix(c(0.4, 2)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test2, y ~ cvar1 + cvar2, n_bootstrap = 30))
  df_test6 <- data.frame(y = rchen_rpr(100, list(2, cvar %*% matrix(c(2, 0.7)))), cvar1 = df$cvar1, cvar2 = df$cvar2)
  expect_snapshot(reg_chen(df_test3, y ~ cvar1 + cvar2, n_bootstrap = 30))
})
